### ISSUE TITLE
[simple-ruby] Leave room for manual overrides

### ISSUE THREAD

**Issue by bert-github** [w3c/simple-ruby#14]
The rules aim to give a reasonable placement in all cases, but, as the introduction mentions, people have used other placements to solve specific problems. One would hope that a system that implements the simple placement rules still allows a typographer to do things differently. Maybe the text should say that somewhere. It currently only says that explicitly for the font size of the ruby, which need not be 1/2.

**Comment by murata2makoto** [comment]
There are many possible design choices, and Kobayashi-sensei chose one of them.  Consensus-based technical changes will simply make the document less useful, I think.

**Comment by r12a** [comment]
What specific technical changes are you concerned about? I don't think any such changes were made to the document.

**Comment by murata2makoto** [comment]
> What specific technical changes are you concerned about?

Allowing manual intervention.    Adding katatsuki.  Mentioning possible customization.  Everything beyond tiny editorial changes.

**Comment by frivoal** [comment]
> Consensus-based technical changes will simply make the document less useful, I think.

I agree. The body of the text should stay unchanged other than tiny editorial changes. The edit I made to close this issue was to make a short mention **in the introduction** that an actual system based on "simple ruby" might customize things. This this is not a normative specification, people can do whatever they want anyway, so to me saying it in the introduction is a way of not repeating it everywhere, which would make things more complicated and dilute professor Kobayashi's approach.

**Comment by r12a** [comment]
I don't believe that the aim of this document was or is to ban all alternatives to what is described, and mandate the model described here as the maximum limit of what can be done with ruby. (I also don't think that would be practical or appropriate.) My understanding is that the document was intended to simply describe one _minimal_ level of support for ruby. 

The recent edits have not changed the model from what it was. The new paragraph in the introduction is merely an acknowledgement that some implementations may go farther that what is described here – it doesn't extend or change the model described here.

Here is the relevant part of that new paragraph:
> The following is a proposal for a simple processing system. The target audience is implementers and specification writers. It is expected that a full system may be more complex that what is described here, both due to the interaction with other features or other writing systems, and because those designing such system may wish to provide alternative options

@murata2makoto if you disagree, please quote the actual text you have a problem with so that we can pinpoint the topic(s) for discussion.  (Note btw, that the latest version of the document is now at https://w3c.github.io/simple-ruby/).

**Comment by murata2makoto** [comment]
@r12a Your paragraph looks fine to me.

**Comment by r12a** [comment]
Ok, thanks. Closing this then. (That para is still in the latest version.)
