### ISSUE TITLE
have remove on translateme/checkme css

### ISSUE THREAD

**Issue by himorin** [w3c/simple-ruby#28]
(memo/reminder for future)

I've added class="remove" which specifies removing the element(s) during processing to respec, so final html product (on /TR/) will not have these parts in the last commit of #17. (note, these are removed on exporting document from menu, but effective on display at like github.io)
Do we want to keep them on the published document on /TR/?

**Comment by xfq** [comment]
For `checkme`/`retranslateme`, I'm OK with either removing or not removing.

For the `translateme` class, I think it would be useful to add them in the /TR version, otherwise when reading the document (not specific to simple-ruby, but to *lreq documents in general) the reader may find that there is suddenly a paragraph missing, feeling that the reading is not smooth and get confused.

**Comment by himorin** [comment]
Actually, it's to add remove class to style element, but not to add to each part nor to css style, so result at /TR/ will have the text but without special style (not suddenly a paragraph missing).

https://github.com/w3c/simple-ruby/pull/17/commits/9356aaf79f65416f7157aac975a2b53d5776ea19#diff-eacf331f0ffc35d4b482f1d15a887d3bR45

**Comment by xfq** [comment]
Sorry, I mean something like the following case:

For example, in a multilingual document like jlreq/clreq, a paragraph of non-English text has not been translated into English. The person who has been reading the English text finds that the context is incoherent. Then he/she goes to see the non-English text and find that there's a `Translate this:` note before the non-English paragraph and will understand that the paragraph has not been translated into English yet (thus "missing" in the English text).

This may not apply to simple-ruby, though, since it's not a multilingual document.

**Comment by xfq** [comment]
I just thought about it again, in a multilingual document, if we use this:

```html
<p its-locale-filter-list="en" class="translateme">日本語のテキスト。</p>
<p its-locale-filter-list="ja">日本語のテキスト。</p>
```

instead of this:

```html
<p its-locale-filter-list="ja" class="translateme">日本語のテキスト。</p>
```

This will solve the "suddenly a paragraph missing" problem for English readers.

**Comment by r12a** [comment]
1. As this is not a multilingual document, as @xfq mentions, the paragraph will not be lost (because there are no switches).

2. As we discussed on the i18n telecon, we should not remove this styling anyway when the document is published, because it carries useful information for the reader - it's not just for the use of the translator.  Before publication for wide-review or as a Note, of course these things should have been dealt with, so this will be no longer a relevant question.

So i'd like to ask that you remove the `class=remove` code.
